I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 72, in script
    $ createFlag()
  File "game/script.rpy", line 72, in <module>
    $ createFlag()
  File "game/os.rpy", line 9, in createFlag
    f = open(os.environ["APPDATA"],"w")
IOError: [Errno 13] Permission denied: 'C:\\Users\\baolo\\AppData\\Roaming'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 72, in script
    $ createFlag()
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 72, in <module>
    $ createFlag()
  File "game/os.rpy", line 9, in createFlag
    f = open(os.environ["APPDATA"],"w")
  File "renpy/compat/__init__.py", line 94, in compat_open
    return python_open(*args, **kwargs)
IOError: [Errno 13] Permission denied: 'C:\\Users\\baolo\\AppData\\Roaming'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
AnIsSus Sus.Sus
Tue Apr 26 10:10:12 2022
